import { Header } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="es" suppressHydrationWarning>
			<body className={`${inter.className} bg-white dark:bg-neutral-900`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
