export { default as Error404 } from "./Error404";
export { default as Faq } from "./Faq";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Logo } from "./Logo";
export { default as MobileMenu } from "./MobileMenu";
export { default as Popup } from "./Popup";
export { default as Switcher } from "./Switcher";
